package com.jcbase.model.base;

import com.jcbase.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppVersion<M extends BaseAppVersion<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setLinkUrl(java.lang.String linkUrl) {
		set("link_url", linkUrl);
	}

	public java.lang.String getLinkUrl() {
		return get("link_url");
	}

	public void setNatureNo(java.lang.Integer natureNo) {
		set("nature_no", natureNo);
	}

	public java.lang.Integer getNatureNo() {
		return get("nature_no");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setVersionNo(java.lang.String versionNo) {
		set("version_no", versionNo);
	}

	public java.lang.String getVersionNo() {
		return get("version_no");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setIsForce(java.lang.Integer isForce) {
		set("is_force", isForce);
	}

	public java.lang.Integer getIsForce() {
		return get("is_force");
	}

}
